/* eslint-disable import/prefer-default-export */
export const AUTHENTICATE = 'AUTHENTICATE'
export const AUTHENTICATE_REQUEST = 'AUTHENTICATE_REQUEST'
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE'
export const SIGNUP = 'SIGNUP'
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE'

export const USER_OBJECT = 'USER_OBJECT'
export const MENU_OBJECT = 'MENU_OBJECT'
