/* eslint-disable import/prefer-default-export */
export const AUTHENTICATE = 'auth/AUTHENTICATE'
export const AUTHENTICATE_REQUEST = 'auth/AUTHENTICATE_REQUEST'
export const AUTHENTICATE_FAILURE = 'auth/AUTHENTICATE_FAILURE'
export const SIGNUP = 'auth/SIGNUP'
export const SIGNUP_REQUEST = 'auth/SIGNUP_REQUEST'
export const SIGNUP_FAILURE = 'auth/SIGNUP_FAILURE'
export const FORGOT_PASSWORD = 'auth/FORGOT_PASSWORD'
export const FORGOT_PASSWORD_REQUEST = 'auth/FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_FAILURE = 'auth/FORGOT_PASSWORD_FAILURE'
export const FORGOT_PASSWORD_CONFIRM = 'auth/FORGOT_PASSWORD_CONFIRM'

export const USER_OBJECT = 'USER_OBJECT'
export const MENU_OBJECT = 'menu/OBJECT'
export const MENU_REFRESH = 'menu/REFRESH'
export const MENU_EXPAND_TOGGLE = 'menu/EXPAND_TOGGLE'

export const SETTINGS_USERS_GRID_LOAD_REQUEST = 'settings/users/GRID_LOAD_REQUEST'
export const SETTINGS_USERS_GRID_LOAD = 'settings/users/GRID_LOAD'
export const SETTINGS_USERS_GRID_LOAD_FAILURE = 'settings/users/GRID_LOAD_FAILURE'
export const SETTINGS_USERS_GRID_DELETE_REQUEST = 'settings/users/GRID_DELETE_REQUEST'
export const SETTINGS_USERS_GRID_DELETE_FAILURE = 'settings/users/GRID_DELETE_FAILURE'
export const SETTINGS_USERS_GRID_ROWS_CHECKED = 'settings/users/GRID_ROWS_CHECKED'
export const SETTINGS_USERS_SORT_CHANGE = 'settings/users/SORT_CHANGE'
export const SETTINGS_USERS_ROWS_CHANGE = 'settings/users/ROWS_CHANGE'
export const SETTINGS_USERS_PAGE_CHANGE = 'settings/users/PAGE_CHANGE'
export const SETTINGS_USERS_PAGE_BEFORE = 'settings/users/PAGE_BEFORE'
export const SETTINGS_USERS_PAGE_NEXT = 'settings/users/PAGE_NEXT'

export const SETTINGS_USERS_ADD = 'settings/users/add'
export const SETTINGS_USERS_DELETE = 'settings/users/delete'
