/* eslint-disable import/prefer-default-export */
export const AUTHENTICATE = 'auth/AUTHENTICATE'
export const AUTHENTICATE_REQUEST = 'auth/AUTHENTICATE_REQUEST'
export const AUTHENTICATE_FAILURE = 'auth/AUTHENTICATE_FAILURE'
export const SIGNUP = 'auth/SIGNUP'
export const SIGNUP_REQUEST = 'auth/SIGNUP_REQUEST'
export const SIGNUP_FAILURE = 'auth/SIGNUP_FAILURE'
export const FORGOT_PASSWORD = 'auth/FORGOT_PASSWORD'
export const FORGOT_PASSWORD_REQUEST = 'auth/FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_FAILURE = 'auth/FORGOT_PASSWORD_FAILURE'

export const USER_OBJECT = 'USER_OBJECT'
export const MENU_OBJECT = 'menu/OBJECT'
export const MENU_REFRESH = 'menu/REFRESH'
export const MENU_EXPAND_TOGGLE = 'menu/EXPAND_TOGGLE'
